dist: trusty
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=mailchain/goswagger-tool
script:
  - docker build -t "${IMAGE_NAME}:latest" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker build -t "${IMAGE_NAME}:${TRAVIS_TAG}" . && docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
    on:
      tags: true